hub:
  image: selenium/hub
  ports:
    - "4444:4444"
target:
  volumes:
    - .:/usr/share/nginx/html
  image: nginx
chrome:
  links:
    - hub:hub
    - target:target
  image: selenium/node-chrome
firefox:
  links:
    - hub:hub
    - target:target
  image: selenium/node-firefox
